Changes
aerogear/ups-test-suite pull request #5
Opened 2016-12-22 19:21 UTC by matzew

* moving mock-data-loader one level up
* in `pom.xml`, using latest jboss-parent
* gitignore changes

@ziccardi @josemigallas  please review/merge

2016-12-22 19:22 UTC, matzew commented
@ziccardi I think we should have a README on the `mock-data-loader` folder about usage

2016-12-22 19:26 UTC, matzew commented
@ziccardi lol - nevermind, just saw it, I think I lost it during strucutre changes :smiley_cat:

2016-12-23 08:02 UTC, josemigallas requested changes
Looks good to me, except for the only comment about readme.

2016-12-23 08:02 UTC, josemigallas commented on README.md
> +A tool to produce mock data (push applications, variants and tokens) can be found into the [mock-data-loader](mock-data-loader) folder.
I would include this section below _Automated Tools_, with the other tools, and change _Automated Tools_ into plain _Tools_.

2016-12-23 08:22 UTC, matzew commented
@josemigallas done!

2016-12-23 09:13 UTC, josemigallas approved these changes

2016-12-23 09:15 UTC, merged